name: Deploy to ECR
# updated secrets
on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: "v.01"
      run: |
        cd application/
        docker build -t 402242685480.dkr.ecr.us-east-1.amazonaws.com/sql:${IMAGE_TAG} -f Dockerfile_mysql .
        docker build -t 402242685480.dkr.ecr.us-east-1.amazonaws.com/app:${IMAGE_TAG} .
        docker push 402242685480.dkr.ecr.us-east-1.amazonaws.com/sql:${IMAGE_TAG}
        docker push 402242685480.dkr.ecr.us-east-1.amazonaws.com/app:${IMAGE_TAG}
